### ISSUE TITLE
Pretrained model, not sure how to load it and finetune

### ISSUE THREAD

**Issue by cdleong** [octanove/shiba#2]
Hello! Thanks for creating this repo! 

I was wondering, how does one load a pretrained model checkpoint so that one can then finetune it on a downstream task, e.g. NER?

Explaining further: Following the instructions in https://github.com/octanove/shiba/blob/main/TRAINING.md, successfully managed to train a model on some new text data. Afterwards, the checkpoints that have been saved, look like this: 
```
total 1.8G
-rw------- 1 root root 1.2G Aug  4 15:37 optimizer.pt
-rw------- 1 root root 608M Aug  4 14:28 pytorch_model.bin
-rw------- 1 root root  15K Aug  4 14:29 rng_state.pth
-rw------- 1 root root  559 Aug  4 14:29 scaler.pt
-rw------- 1 root root  623 Aug  4 14:29 scheduler.pt
-rw------- 1 root root  25K Aug  4 14:29 trainer_state.json
-rw------- 1 root root 2.5K Aug  4 14:29 training_args.bin
```

How does one take that, and _finetune it_ on, say, an NER task? 

I tried many variations on 
```python
shiba_model = Shiba()
pretrained_model_folder= path to the directory above
torch_model = torch.load(thingtoload) 
shiba_model.load_state_dict(torch_model)
```

...where thingtoload is every file in the folder. Each time, I get a different error, e.g. unexpected keys, etc. 

I also tried manually editing train.py in shiba code to do `torch.save(model.state_dict(), "state_dict.pt")`, and that allows me to at least load in a `ShibaForAutoregressiveLanguageModeling` like this: 
```python

thingtoload = Path(pretrained_model_folder) / "state_dict.pt" 
MAX_JP_CODEPOINT = 0x9faf
from shiba import ShibaForAutoregressiveLanguageModeling
model = ShibaForAutoregressiveLanguageModeling(MAX_JP_CODEPOINT )
model.load_state_dict(torch.load(thingtoload))
```
Which gives me "all keys matched successfully"

But how do I create a `Shiba`, or a `ShibaForClassification`, or a `ShibaForSequenceLabeling`? How do I load in the pretrained model I created, into one of those?

**Comment by cdleong** [comment]
Example error is below. Something I noticed is that all the keys in _my_ state_dict start with `shiba_model`.  

Whereas the keys in https://storage.googleapis.com/shiba.octanove.com/published_checkpoints/shiba_check45k.pt do not have this prefix. 
```
RuntimeError: Error(s) in loading state_dict for Shiba:
	Missing key(s) in state_dict: "embedder.buckets.0.weight", "embedder.buckets.1.weight", "embedder.buckets.2.weight", "embedder.buckets.3.weight", "embedder.buckets.4.weight", "embedder.buckets.5.weight", "embedder.buckets.6.weight", "embedder.buckets.7.weight", "position_embedder.embedding.weight", "embedder_ln.weight", "embedder_ln.bias", "local_transformer.self_attn.query.weight", "local_transformer.self_attn.query.bias", "local_transformer.self_attn.key.weight", "local_transformer.self_attn.key.bias", "local_transformer.self_attn.value.weight", "local_transformer.self_attn.value.bias", "local_transformer.self_attn.attn.rel_pos.inv_freq", "local_transformer.linear1.weight", "local_transformer.linear1.bias", "local_transformer.linear2.weight", "local_transformer.linear2.bias", "local_transformer.norm1.weight", "local_transformer.norm1.bias", "local_transformer.norm2.weight", "local_transformer.norm2.bias", "downsample_conv.weight", "downsample_conv.bias", "downsample_ln.weight", "downsample_ln.bias", "cls_linear.weight", "cls_linear.bias", "deep_transformer.layers.0.self_attn.in_proj_weight", "deep_transformer.layers.0.self_attn.in_proj_bias", "deep_transformer.layers.0.self_attn.out_proj.weight", "deep_transformer.layers.0.self_attn.out_proj.bias", "deep_transformer.layers.0.linear1.weight", "deep_transformer.layers.0.linear1.bias", "deep_transformer.layers.0.linear2.weight", "deep_transformer.layers.0.linear2.bias", "deep_transformer.layers.0.norm1.weight", "deep_trans...
	Unexpected key(s) in state_dict: "shiba_model.embedder.buckets.0.weight", "shiba_model.embedder.buckets.1.weight", "shiba_model.embedder.buckets.2.weight", "shiba_model.embedder.buckets.3.weight", "shiba_model.embedder.buckets.4.weight", "shiba_model.embedder.buckets.5.weight", "shiba_model.embedder.buckets.6.weight", "shiba_model.embedder.buckets.7.weight", "shiba_model.position_embedder.embedding.weight", "shiba_model.embedder_ln.weight", "shiba_model.embedder_ln.bias", "shiba_model.local_transformer.self_attn.query.weight", "shiba_model.local_transformer.self_attn.query.bias", "shiba_model.local_transformer.self_attn.key.weight", "shiba_model.local_transformer.self_attn.key.bias", "shiba_model.local_transformer.self_attn.value.weight", "shiba_model.local_transformer.self_attn.value.bias", "shiba_model.local_transformer.self_attn.attn.rel_pos.inv_freq", "shiba_model.local_transformer.linear1.weight", "shiba_model.local_transformer.linear1.bias", "shiba_model.local_transformer.linear2.weight", "shiba_model.local_transformer.linear2.bias", "shiba_model.local_transformer.norm1.weight", "shiba_model.local_transformer.norm1.bias", "shiba_model.local_transformer.norm2.weight", "shiba_model.local_transformer.norm2.bias", "shiba_model.downsample_conv.weight", "shiba_model.downsample_conv.bias", "shiba_model.downsample_ln.weight", "shiba_model.downsample_ln.bias", "shiba_model.cls_linear.weight", "shiba_model.cls_linear.bias", "shiba_model.deep_transformer.layers.0.self_attn.in_...

**Comment by cdleong** [comment]
Perhaps if I just... rename all the keys? https://gist.github.com/the-bass/0bf8aaa302f9ba0d26798b11e4dd73e3

**Comment by cdleong** [comment]
Related: https://discuss.pytorch.org/t/prefix-parameter-names-in-saved-model-if-trained-by-multi-gpu/494/4

**Comment by cdleong** [comment]
OK, I gave "manually remove the key prefixes" a try, thus: 
```python
pretrained_shiba_from_shiba_repo = torch.load("pretrained_shiba.pt")
print(pretrained_shiba_from_shiba_repo.keys())
pretrained_shiba_from_me = torch.load("path/to/my/state_dict.pt")
print(pretrained_shiba_from_me.keys())

# remove the prefixes
# https://discuss.pytorch.org/t/prefix-parameter-names-in-saved-model-if-trained-by-multi-gpu/494/4
pretrained_shiba_from_me_with_fixed_keys = {k.partition("shiba_model.")[2]:pretrained_shiba_from_me[k] for k in pretrained_shiba_from_me.keys()}

# if I print print(pretrained_shiba_from_me.keys()) at this point, there is one key at the end: "", but it is otherwise identical to the one from the shiba repo
# I believe that the partition ends up deleting keys like "autregressive_encoder.norm2.bias", reducing them all to ""
_ = pretrained_shiba_from_me_with_fixed_keys.pop("", None)

print(pretrained_shiba_from_shiba_repo.keys())
print(pretrained_shiba_from_me.keys())
```

And then it seems to work. Can anyone confirm whether this is the right way to do it? It seems hacky. 

But then when I print the keys of https://storage.googleapis.com/shiba.octanove.com/published_checkpoints/shiba_check45k.pt and this "fixed" version of mine, they seem to have exactly the same list of keys after doing this, so... I guess it works?

**Comment by cdleong** [comment]
After doing the above, 
```
from shiba import ShibaForClassification
cls_model = ShibaForClassification(vocab_size=3)
cls_model.shiba_model.load_state_dict(pretrained_shiba_from_me_with_fixed_keys)
```
outputs "all keys matched successfully."

Again, this seems hacky, but it seems to work. 

This means that the answer to my original question seems to be: 
1. `state_dict =torch.load("path to pytorch_model.bin"`
2. edit the resulting `state_dict` to drop out the prefixes and pop the key ""
3. proceed from there

**Comment by Mindful** [comment]
I likely won't be able to respond in detail until this weekend, but

1. You seem to have solved this problem for yourself (although do let me know if you still have questions) 
2. At the very least, you're on the right track - manually working with the state dict is the only way I know of to do this

For what it's worth, when we pull the base model state dict out of the language model state dict, we basically do the same thing. The code is here: https://github.com/octanove/shiba/blob/main/training/helpers.py#L95 

I agree it feels hacky though.

**Comment by cdleong** [comment]
Josh,

Thanks very much for the reply! I'm not all that experienced with this
stuff, it's reassuring to know I'm on the right track. And I didn't notice
that function in the helpers file! Nice!

If you do have bandwidth, I would love your thoughts on how to fine-tune
the model on an NER task. Specifically, I'm trying to do MasakhaNER.

The original version of the data is in
https://github.com/cdleong/masakhane-ner/tree/main/data/swa, with one label
per word.

I edited the data to have per-character labels here:
https://github.com/cdleong/masakhane-ner/tree/main/data/swa_no_word_boundaries

https://github.com/cdleong/masakhane-ner/blob/main/custom_huggingface_loading_script.py
is a "custom loading script" (
https://huggingface.co/docs/datasets/loading_datasets.html)

Probably too much detail there, basically my question is, what would be
your high level approach? Load in the characters with labels, then use a
ShibaForSequenceLabeling maybe?

**Comment by Mindful** [comment]
An in-depth explanation of best practices for NER is too much for a Github issues comment thread (and there are people way more qualified to than me to give said explanation), but in generally modern NER is done as a sequence labeling task, so I think you're on the right track. Treating the problem as a character-level sequence labeling and using ShibaForSequenceLabeling as-is will probably work fine, although note that if you want to add a more complicated head on top of the pretrained encoder that's really easy to do as well - the task-specific models are [super simple](https://github.com/octanove/shiba/blob/main/shiba/model.py#L285). 

I assume you are using Shiba over token-level models because you think that character-level information will be helpful - this seems like a good intuition for NER-based tasks given that named entities are often uncommon/not present in training data and don't split cleanly into tokens. That said, if your final scoring is token-based and tokenization is easy/deterministic for the languages you're working with,  remember that you can always fall back to token-level eval by using the most common label among characters in a token or something similar (the model might even score slightly better this way).

Also, just to double check here
> Explaining further: Following the instructions in https://github.com/octanove/shiba/blob/main/TRAINING.md, successfully managed to train a model on some new text data. Afterwards, the checkpoints that have been saved, look like this:

You didn't use our preprocessing script as-is, right? The actual model training is fairly language agnostic (though character-level masking is probably better for some languages than others) but the preprocessing scripts expect Japanese input, and will probably produce weird output for anything else.  At the very least, it might not hurt to take the language-model as is and pass in a few pieces of text with masks in your target language(s) to make sure it's producing sane output. 

That's about all I can think of in terms of things to watch out for. Hope this is helpful.

**Comment by cdleong** [comment]
Yes, that's, quite helpful, thank you! 

As for the preprocessing script, I didn't use it, no - I just ran it once to check what it outputs: As far as I can tell this basically just .txt file, each line being a data item/sentence. Then we pass that to `to_examples.py`, which reformats it to a .jsonl file. 

So I just took https://huggingface.co/datasets/swahili, and output it to a .txt file in the same format, and put that into the `to_examples` script.

Regarding final scoring, it's an interesting question to be sure. Given a data item like 

```
John B-PER
Smith I-PER
eats O
apples O
. O

```

I converted it to 

```
J B-PER
o I-PER
h I-PER
n I-PER
S I-PER
etc
```
So I've been thinking about how to properly score that. For example, if the model outputs the correct labels for every character in "JohnSmith" except for one, is it 8/9 characters correct, or 0/1 entities correct? An interesting question, I guess I'll report both numbers. 

As for actually setting up the finetuning on NER, we are giving it a go based on https://github.com/octanove/shiba/blob/main/training/finetune_word_segmentation.py! It seems like a good base to build off of - we've got more labels than "beginning of word or not beginning of word", so we had to mess with that, and we edited `process_examples()` to give the leading `[CLS]` token the label "O" for outside, but otherwise it seems really close. 

Actually now that I think about it, we could use the same dataset to train a word segmentation model, couldn't we? Just re-label the dataset to mark the start of each word. That would be pretty cool!

Anyway, thanks for all the info! Let me know if there's anything we can contribute back, e.g. when we finish our finetune_on_ner.py, shall we try to merge that back in, for example?

**Comment by Mindful** [comment]
Sounds like you have preprocessing worked out.

> So I've been thinking about how to properly score that. For example, if the model outputs the correct labels for every character in "JohnSmith" except for one, is it 8/9 characters correct, or 0/1 entities correct? An interesting question, I guess I'll report both numbers.

This is a good question. Reporting both scores is probably the safest way to do this, but I think specifically for the token level score you could either
1. Make all the character-level labels in a token the same as the token-level label (I.E. John would be B-PER *4), and then label token with the most common character level label
2. Leave your labeling scheme as is, and just label tokens with the label of their first character, or allow B-labels on the first character to override other character level labels

> Actually now that I think about it, we could use the same dataset to train a word segmentation model, couldn't we? Just re-label the dataset to mark the start of each word. That would be pretty cool!

If you're working with languages that mostly split words on whitespace I think training a model (especially one as big as SHIBA) is potentially overkill, although it should certainly work. Trying to produce a more flexible wordseg model for Japanese was actually one of the original motivations for this project, so if you end up doing wordseg on a language with a lot of non-whitespace splits I would be curious to hear how it turns out. 

> Anyway, thanks for all the info! Let me know if there's anything we can contribute back, e.g. when we finish our finetune_on_ner.py, shall we try to merge that back in, for example?

Thanks! This repo is mostly intended to contain code relating to the original experiments/training so I don't think merging new finetuning scripts make sense right now, but I'll be curious to hear how things turn out. If you have a public repo with Shiba's pypy package listed as a dependency it should automatically show up as a project using Shiba, although if you're using a lot of training code then the pypy package may not make sense.

**Comment by cdleong** [comment]
Appreciate the advice! The basic concept we're looking at is 
1. Convert speech data to IPA phonemes with Allosaurus. Unfortunately that means we lose all the word boundaries because, well, people don't pronounce whitespace. 
2. If only there were language models that worked on streams of characters without word boundaries, eh? Let's try training SHIBA on those streams of IPA phones!
3. See if it works by looking at the MasakhaNER scores. 

So Swahili normally does split words on whitespace, but when we feed it Swahili _audio_ data, we don't have those whitespace splits. It would be really interesting to see if word segmentation is possible, like, _at all_, given enough phonemes. I'll let you know how it goes!

**Comment by cdleong** [comment]
One question: do we need to save off any particular items in the pretraining step, other than the pytorch_model.bin? For example, the tokenizer or tokenizer vocab?

**Comment by Mindful** [comment]
Nope, just the model. Tokenizer has no state of any kind, and consequently no vocab.

**Comment by cdleong** [comment]
OK, here's something, I'm getting NaN loss in finetuning. Any idea what might be causing that? 

Pretrained model is here: https://drive.google.com/file/d/10eJ0GMx4QQZ2pyWIVaJdACWM7R-MtudK/view?usp=sharing
It was pretrained on https://huggingface.co/datasets/swahili dataset, (with spaces removed), for 5k steps, mostly default settings I think. 

Here's a colab notebook where I try to run finetuning: https://colab.research.google.com/drive/12OSzO3FZFDBIUhb3s31KPjl3wV__st4q?usp=sharing, 

I turned on debug="underflow_overflow" and saw this:
![image](https://user-images.githubusercontent.com/4109253/129067132-a36f971e-11b1-4070-9e9b-5b86e09278a4.png)

**Comment by cdleong** [comment]
Found a couple things. 
1. Above is not what usually happens, only what happens when you re-run the cell a second time. 
2. If you reload the notebook, or just reload from the pytorch_model.bin first, it'll go for a few batches before getting nan loss: 
```
output[0] has nans
output[1] has nans

Detected inf/nan during batch_number=130
Last 21 forward frames:
abs min  abs max  metadata
                  shiba_model.local_transformer.self_attn.key Linear
2.45e-08 6.35e-02 weight
4.79e-05 4.30e-02 bias
1.04e-06 7.47e+00 input[0]
8.52e-07 4.24e+00 output
                  shiba_model.local_transformer.self_attn.value Linear
2.45e-09 2.64e-01 weight
7.71e-06 4.82e-02 bias
1.04e-06 7.47e+00 input[0]
2.32e-06 1.65e+01 output
                  shiba_model.local_transformer.self_attn.attn.rel_pos SinusoidalEmbeddings
3.98e-07 4.52e+00 input[0]
0.00e+00 1.92e+02 output
                  shiba_model.local_transformer.self_attn.attn.dropout Dropout
0.00e+00 1.95e-01 input[0]
0.00e+00 2.17e-01 output
                  shiba_model.local_transformer.self_attn.attn LocalAttention
3.98e-07 4.52e+00 input[0]
8.52e-07 4.24e+00 input[1]
2.32e-06 1.65e+01 input[2]
0.00e+00 1.00e+00 input[3]
1.64e-07 2.74e+00 output
                  shiba_model.local_transformer.self_attn LocalSelfAttention
1.04e-06 7.47e+00 input[0]
1.64e-07 2.74e+00 output
                  shiba_model.local_transformer.dropout1 Dropout
1.64e-07 2.74e+00 input[0]
0.00e+00 3.05e+00 output
                  shiba_model.local_transformer.norm1 LayerNorm
8.81e-01 1.26e+00 weight
7.33e-05 5.22e-01 bias
5.51e-06 7.78e+00 input[0]
1.09e-06 6.49e+00 output
                  shiba_model.local_transformer.linear1 Linear
1.71e-08 1.60e-01 weight
2.29e-05 1.07e-01 bias
1.09e-06 6.49e+00 input[0]
7.60e-07 1.05e+01 output
                  shiba_model.local_transformer.dropout Dropout
7.23e-25 8.51e+00 input[0]
0.00e+00 9.45e+00 output
                  shiba_model.local_transformer.linear2 Linear
2.03e-08 5.40e-01 weight
3.23e-05 3.19e-01 bias
0.00e+00 9.45e+00 input[0]
7.43e-07 6.06e+01 output
                  shiba_model.local_transformer.dropout2 Dropout
7.43e-07 6.06e+01 input[0]
0.00e+00 6.74e+01 output
                  shiba_model.local_transformer.norm2 LayerNorm
3.67e-01 9.52e-01 weight
1.61e-05 2.50e-01 bias
5.96e-07 6.75e+01 input[0]
6.05e-08 1.11e+01 output
                  shiba_model.local_transformer LocalTransformerEncoderLayer
1.04e-06 7.47e+00 input[0]
0.00e+00 1.00e+00 input[1]
6.05e-08 1.11e+01 output
                  shiba_model.cls_linear Linear
5.92e-08 3.55e-02 weight
3.20e-05 3.60e-02 bias
3.41e-04 4.39e+00 input[0]
7.81e-05 1.58e+00 output
                  shiba_model.dropout Dropout
7.81e-05 1.58e+00 input[0]
0.00e+00 1.76e+00 output
                  shiba_model.downsample_conv Conv1d
4.68e-09 1.27e-01 weight
3.45e-06 4.72e-02 bias
6.05e-08 1.11e+01 input[0]
1.37e-05 1.17e+01 output
                  shiba_model.activation GELU
1.37e-05 1.17e+01 input[0]
1.31e-30 1.05e+01 output
                  shiba_model.downsample_ln LayerNorm
9.15e-01 1.08e+00 weight
3.87e-05 5.58e-02 bias
1.31e-30 1.05e+01 input[0]
2.10e-06 9.04e+00 output
                  shiba_model.downsample_attention_pool MaxPool1d
0.00e+00 1.00e+00 input[0]
0.00e+00 1.00e+00 output
                  shiba_model.deep_transformer.layers.0.self_attn MultiheadAttention
2.32e-08 1.20e-01 in_proj_weight
1.74e-07 7.76e-02 in_proj_bias
0.00e+00 9.04e+00 input[0]
0.00e+00 9.04e+00 input[1]
0.00e+00 9.04e+00 input[2]
     nan      nan output[0]
     nan      nan output[1]
```
3. It always crashes on the same batch number, regardless of what learning rate I give it. 
4. `train_dataset=dep['test'],` will crash on batch 2, instead of 130
5. Editing the data collator, this is the exact batch on which it crashes: 
```
torch.Size([8, 203])
Imetayarishwanamwandishiwetu,Washington,DC.���������������������������������������������������������������������������������������������������������������������������������������������������������������
KauliyamabalozinchiniTanzania“Kwakawaida,naanzasikuyangukwakusomabaadhiyamagazeti,likiwemogazetilililofungiwalaTheCitizen,“BaloziwaUingerezanchiniTanzaniaSarahCookeameandikakatikaakauntiyakeyaTwitter.��
Kunabaadhiyafilamutunazozitengenezazinazohitajiusirimkubwakatikamaandaliziyake.���������������������������������������������������������������������������������������������������������������������������
vyombovyahabarivyataifalaChinaijumaavimeripotikwambauchunguziutafanywakufuatiakesiyaDr.�������������������������������������������������������������������������������������������������������������������
Watuwatabakazote,jinsiazotenarangizotewameunganakuombamageuzi,""""amesemaPhilonise.�����������������������������������������������������������������������������������������������������������������������
7.��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
JioniJumanne,MwakilishiwaBarazalaWawakilishiMichaelMcCaul,kiongoziwaRepublikankatikaKamatiyaMamboyaNje,amesemauchunguziwakumuondoaraismadarakani""""unaoendeleakwafaraghaambapoilitakiwaufanyikehadharani.
Nyotamchekeshajikwenyejukwaa,filamunatelevisheniJerryStilleramefarikiakiwanaumriwamiaka92.����������������������������������������������������������������������������������������������������������������
```
6. Similarly, the validation set crashes on this one: 
```
TrumpanayegombaniakiticharaisMarekanimwaka2020alisemahatofanyakazinawa-Demokratsjuuyamasualayakukarabatimiundombinuaujambojinginelolotehadiuchunguziunaofanywajuuyakeunamalizika.�������������������������������������������������������������������������������
Alisemawameshapatataarifazanjamayauitishwajiwamkutanomkuuwataifa""""feki""""waLipumbanagengelake,lakiniMei9,mwaka2018yeyepamojanaNaibuKatibuMkuu(Bara),NassorAhmedMazrui,walifunguashaurimamanamba84/2018nashauridogonamba248/2018kupingakuitishamkutanohuofeki.
Pigahesabuyamiaka5uone.�����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
BaadaekiongozihuyowaChinaalikutananaWaziriMkuuwaEthopiaAbiyAhmednaMkurugenziMtendajiwaIMF,BiChristianLagardekwamazungumzombalimbali.����������������������������������������������������������������������������������������������������������������������������
AlikuwaameahidikuwepoilikubadilishanamadarakakwanjiayautulivuhukoDRCtangunchihiyokupatauhuruwakekutokaUbelgijimwaka1960.����������������������������������������������������������������������������������������������������������������������������������������
4.��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
Kwaninimnachukuwafedhazawabungehawa?����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
StateDepartment,demandingAlekseiBurkov'srightsberespected.������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

Working theory, if you have a data item like 
```
7.
```
it doesn't like that!

**Comment by cdleong** [comment]
The theory seems to hold. If I filter out data items with less than 5 nonzero values in the Data Collator, training proceeds without incident.

**Comment by Mindful** [comment]
I am once again probably going to be unable to make a detailed comment until the weekend; my initial suggestion was to try adjusting the learning rate, but it seems like you've tried that. The data item that you gave as an example of something going wrong looks blank (?), although I'm not sure if it's just characters not rendering.

Based on your last comment it looks like you solved the issue - which is great! If the issue is cases where 5 or less items (I actually suspect it's 4 or less, because SHIBA downsamples 4x), it's likely that this is an issue with the downsampling/upsampling code. There may not be a good way to properly process examples shorter than the downsampling rate, but if this is really the issue I should probably add some code to throw an exception with a more informative error. Sorry about that.

**Comment by cdleong** [comment]
Not _quite_ blank, there's exactly 2 characters at the beginning, `7.`, which got padded out with zeroes! 

The downsampling thing makes sense! I can reset the threshold to test that theory. If I filter for 4 or less, then 3 or less, we can check exactly where it breaks. I'll go give it a try and update here!

**Comment by cdleong** [comment]
Keeping examples greater than 3 characters (that is, 4 or more): runs OK
Keeping examples greater than 2 characters (3 or more): Still runs OK. Huh!
Keeping examples 2 or more long: inf/nan error. 

The following data item is fine: 
```
62.
```
The following consistently causes a nan: 
```
7.
```

Edit: Oh, 3 or more works, because it's actually got the [CLS] token added in front, of course. 3+1 is 4.

**Comment by cdleong** [comment]
Full Traceback, in case that's helpful
```python
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-89-89dec07100f4> in <module>()
     10                   )
     11 
---> 12 trainer.train()

12 frames

/usr/local/lib/python3.7/dist-packages/transformers/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1284                         tr_loss += self.training_step(model, inputs)
   1285                 else:
-> 1286                     tr_loss += self.training_step(model, inputs)
   1287                 self.current_flos += float(self.floating_point_ops(inputs))
   1288 

/usr/local/lib/python3.7/dist-packages/transformers/trainer.py in training_step(self, model, inputs)
   1777                 loss = self.compute_loss(model, inputs)
   1778         else:
-> 1779             loss = self.compute_loss(model, inputs)
   1780 
   1781         if self.args.n_gpu > 1:

/usr/local/lib/python3.7/dist-packages/transformers/trainer.py in compute_loss(self, model, inputs, return_outputs)
   1809         else:
   1810             labels = None
-> 1811         outputs = model(**inputs)
   1812         # Save past state if it exists
   1813         # TODO: this needs to be fixed and made cleaner later.

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1069             input = bw_hook.setup_input_hook(input)
   1070 
-> 1071         result = forward_call(*input, **kwargs)
   1072         if _global_forward_hooks or self._forward_hooks:
   1073             for hook in itertools.chain(

/usr/local/lib/python3.7/dist-packages/shiba/model.py in forward(self, input_ids, labels, attention_mask)
    297     def forward(self, input_ids: torch.Tensor, labels: Optional[torch.Tensor],
    298                 attention_mask: torch.Tensor) -> Tuple:
--> 299         embeddings = self.shiba_model(input_ids, attention_mask, None)['embeddings']
    300 
    301         label_hidden_states = self.label_layer(self.dropout(embeddings))

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1069             input = bw_hook.setup_input_hook(input)
   1070 
-> 1071         result = forward_call(*input, **kwargs)
   1072         if _global_forward_hooks or self._forward_hooks:
   1073             for hook in itertools.chain(

/usr/local/lib/python3.7/dist-packages/shiba/model.py in forward(self, input_ids, attention_mask, predict_indices)
    183             # anything other than "src_key_padding_mask" this will break
    184             contextualized_molecules = self.deep_transformer(molecules.transpose(0, 1),
--> 185                                                         src_key_padding_mask=molecule_attention_mask).transpose(0, 1)  # h`_down
    186         else:
    187             contextualized_molecules = self.deep_transformer(molecules, src_key_padding_mask=molecule_attention_mask)

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1069             input = bw_hook.setup_input_hook(input)
   1070 
-> 1071         result = forward_call(*input, **kwargs)
   1072         if _global_forward_hooks or self._forward_hooks:
   1073             for hook in itertools.chain(

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py in forward(self, src, mask, src_key_padding_mask)
    193 
    194         for mod in self.layers:
--> 195             output = mod(output, src_mask=mask, src_key_padding_mask=src_key_padding_mask)
    196 
    197         if self.norm is not None:

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1069             input = bw_hook.setup_input_hook(input)
   1070 
-> 1071         result = forward_call(*input, **kwargs)
   1072         if _global_forward_hooks or self._forward_hooks:
   1073             for hook in itertools.chain(

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/transformer.py in forward(self, src, src_mask, src_key_padding_mask)
    319         """
    320         src2 = self.self_attn(src, src, src, attn_mask=src_mask,
--> 321                               key_padding_mask=src_key_padding_mask)[0]
    322         src = src + self.dropout1(src2)
    323         src = self.norm1(src)

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1074                     _global_forward_hooks.values(),
   1075                     self._forward_hooks.values()):
-> 1076                 hook_result = hook(self, input, result)
   1077                 if hook_result is not None:
   1078                     result = hook_result

/usr/local/lib/python3.7/dist-packages/transformers/debug_utils.py in forward_hook(self, module, input, output)
    270             # now we can abort, as it's pointless to continue running
    271             raise ValueError(
--> 272                 "DebugUnderflowOverflow: inf/nan detected, aborting as there is no point running further. "
    273                 "Please scroll up above this traceback to see the activation values prior to this event."
    274             )

ValueError: DebugUnderflowOverflow: inf/nan detected, aborting as there is no point running further. Please scroll up above this traceback to see the activation values prior to this event.


```

**Comment by cdleong** [comment]
Just remembered that a 3-long item is actually going to become 4-long, when `[CLS]` gets added in. So I think the 4x downsampling theory is consistent with that!
