### ISSUE TITLE
Training Data link not working

### ISSUE THREAD

**Issue by VisionOra** [octanove/shiba#5]
Hi, I need to see the input data format. But the link mentioned in `training.md` is not working, can you please provide me the link. Thanks in advance.

https://github.com/octanove/shiba/blob/main/TRAINING.md#:~:text=wget%20https%3A//dumps.wikimedia.org/other/cirrussearch/current/jawiki%2D20210510%2Dcirrussearch%2Dcontent.json.gz

this link 
```
wget https://dumps.wikimedia.org/other/cirrussearch/current/jawiki-20210510-cirrussearch-content.json.gz

```

**Comment by Mindful** [comment]
@SohaibAnwaar Hi there, thanks for opening an issue.

It does indeed look like version of the Japanese wikipedia dump that we used as training data is no longer available - sorry about that! However, the wikimedia dumps still exist, and you can find an index of the latest dumps at https://dumps.wikimedia.org/other/cirrussearch/current/. 

For the Japanese wikipedia dump, it looks like the latest is currently https://dumps.wikimedia.org/other/cirrussearch/current/jawiki-20230306-cirrussearch-content.json.gz, but even if that changes in the future you should be able to find the latest data by searching for "jawiki" in the index.

**Comment by Mindful** [comment]
Closing this, please feel free to open another if there are other issues.

**Comment by VisionOra** [comment]
sure thank you
